/**
 * Local backup engine: any client (CLI, IDE extension, MCP server itself) that
 * is about to mutate a file on disk MUST first call createBackup(). The backup
 * lives under .modelbound/backups/<rel>/<iso>-<sha7>.bak and is referenced in
 * a sibling manifest.json so the user can list / restore from any client.
 *
 * Why a shared engine?
 *  - One on-disk layout means `modelbound backup list` works regardless of
 *    which tool wrote the backup.
 *  - Centralised path safety: no writes outside the project root, no symlink
 *    traversal, no .. segments. Each client gets the same guarantee.
 *  - 0600 permissions on POSIX so other users can't read sensitive skills.
 *
 * No external deps — uses only Node stdlib so this can run inside the MCP
 * server's stdio process, the CLI, or a VS Code extension worker.
 */
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

export interface BackupRecord {
  rel: string;             // path relative to project root
  backup_path: string;     // path to the .bak file
  sha7: string;            // short sha of original content
  size: number;
  created_at: string;      // ISO timestamp
  parent_version: string | null;
  source: "cli" | "mcp" | "ide" | "plugin";
}

export interface BackupOptions {
  root: string;            // project root (typically cwd)
  source: BackupRecord["source"];
  parentVersion?: string | null;
}

const BACKUP_DIR = ".modelbound/backups";
const MANIFEST = "manifest.json";

function sha7(buf: Buffer | string): string {
  const h = createHash("sha256");
  h.update(buf);
  return h.digest("hex").slice(0, 7);
}

function isInside(parent: string, child: string): boolean {
  const rel = relative(parent, child);
  return !!rel && !rel.startsWith("..") && !rel.startsWith(sep);
}

/** Create a backup for `absPath` under `<root>/.modelbound/backups/...`. */
export async function createBackup(absPath: string, opts: BackupOptions): Promise<BackupRecord> {
  const root = resolve(opts.root);
  const target = resolve(absPath);
  if (!isInside(root, target)) {
    throw new Error(`refuse to back up file outside project root: ${absPath}`);
  }
  const content = await fs.readFile(target);
  const rel = relative(root, target);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const short = sha7(content);
  const backupDir = join(root, BACKUP_DIR, rel);
  await fs.mkdir(backupDir, { recursive: true });
  const backupPath = join(backupDir, `${stamp}-${short}.bak`);
  await fs.writeFile(backupPath, content, { mode: 0o600 });

  const record: BackupRecord = {
    rel,
    backup_path: relative(root, backupPath),
    sha7: short,
    size: content.byteLength,
    created_at: new Date().toISOString(),
    parent_version: opts.parentVersion ?? null,
    source: opts.source,
  };
  await appendManifest(root, record);
  await ensureGitignore(root);
  return record;
}

async function appendManifest(root: string, record: BackupRecord) {
  const manifestPath = join(root, BACKUP_DIR, MANIFEST);
  let prev: BackupRecord[] = [];
  try {
    prev = JSON.parse(await fs.readFile(manifestPath, "utf8"));
    if (!Array.isArray(prev)) prev = [];
  } catch { /* fresh */ }
  prev.push(record);
  // Cap at 1000 entries to keep the file tiny.
  if (prev.length > 1000) prev = prev.slice(prev.length - 1000);
  await fs.mkdir(dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, JSON.stringify(prev, null, 2), { mode: 0o600 });
}

async function ensureGitignore(root: string) {
  const giPath = join(root, BACKUP_DIR, ".gitignore");
  try {
    await fs.access(giPath);
    return;
  } catch { /* missing */ }
  await fs.mkdir(dirname(giPath), { recursive: true });
  await fs.writeFile(giPath, "# Auto-generated by ModelBound — backups are local-only.\n*\n!.gitignore\n");
}

export async function listBackups(root: string): Promise<BackupRecord[]> {
  try {
    const txt = await fs.readFile(join(root, BACKUP_DIR, MANIFEST), "utf8");
    const arr = JSON.parse(txt);
    return Array.isArray(arr) ? arr : [];
  } catch { return []; }
}

/** Restore a previously created backup back to its original path. The CURRENT
 * contents of the original path are themselves backed up first so the user
 * always has an undo step. Returns the new "undo" record. */
export async function restoreBackup(root: string, backupRelPath: string, source: BackupRecord["source"]): Promise<{ restored: string; undo: BackupRecord }> {
  const root_ = resolve(root);
  const backupAbs = resolve(root_, backupRelPath);
  if (!isInside(root_, backupAbs)) throw new Error("backup path outside project root");

  const manifest = await listBackups(root_);
  const entry = manifest.find((m) => m.backup_path === backupRelPath);
  if (!entry) throw new Error(`backup not found in manifest: ${backupRelPath}`);

  const originalAbs = resolve(root_, entry.rel);
  // Take an undo snapshot of the current file (if any) before overwriting.
  let undo: BackupRecord;
  try {
    undo = await createBackup(originalAbs, { root: root_, source, parentVersion: entry.sha7 });
  } catch {
    // Original may not exist yet (e.g. deleted file) — synthesize an empty undo record.
    undo = {
      rel: entry.rel, backup_path: "", sha7: "", size: 0,
      created_at: new Date().toISOString(), parent_version: entry.sha7, source,
    };
  }

  const data = await fs.readFile(backupAbs);
  await fs.mkdir(dirname(originalAbs), { recursive: true });
  await fs.writeFile(originalAbs, data);
  return { restored: entry.rel, undo };
}
